// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BaseProtocol.proto

package cn.zrtcx.miniHDFS.protobuf;

public final class BaseProtocolProbuf {
  private BaseProtocolProbuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PathProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.zrtcx.miniHDFS.protobuf.PathProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string src = 1;</code>
     */
    java.lang.String getSrc();
    /**
     * <code>string src = 1;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    /**
     * <code>bool hasPermission = 2;</code>
     */
    boolean getHasPermission();
  }
  /**
   * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.PathProto}
   */
  public  static final class PathProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.zrtcx.miniHDFS.protobuf.PathProto)
      PathProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PathProto.newBuilder() to construct.
    private PathProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PathProto() {
      src_ = "";
      hasPermission_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PathProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              src_ = s;
              break;
            }
            case 16: {

              hasPermission_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.Builder.class);
    }

    public static final int SRC_FIELD_NUMBER = 1;
    private volatile java.lang.Object src_;
    /**
     * <code>string src = 1;</code>
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        src_ = s;
        return s;
      }
    }
    /**
     * <code>string src = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASPERMISSION_FIELD_NUMBER = 2;
    private boolean hasPermission_;
    /**
     * <code>bool hasPermission = 2;</code>
     */
    public boolean getHasPermission() {
      return hasPermission_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSrcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, src_);
      }
      if (hasPermission_ != false) {
        output.writeBool(2, hasPermission_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSrcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, src_);
      }
      if (hasPermission_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, hasPermission_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto)) {
        return super.equals(obj);
      }
      cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto other = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto) obj;

      boolean result = true;
      result = result && getSrc()
          .equals(other.getSrc());
      result = result && (getHasPermission()
          == other.getHasPermission());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRC_FIELD_NUMBER;
      hash = (53 * hash) + getSrc().hashCode();
      hash = (37 * hash) + HASPERMISSION_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getHasPermission());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.PathProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.zrtcx.miniHDFS.protobuf.PathProto)
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.Builder.class);
      }

      // Construct using cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        src_ = "";

        hasPermission_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto getDefaultInstanceForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.getDefaultInstance();
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto build() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto buildPartial() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto result = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto(this);
        result.src_ = src_;
        result.hasPermission_ = hasPermission_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto) {
          return mergeFrom((cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto other) {
        if (other == cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto.getDefaultInstance()) return this;
        if (!other.getSrc().isEmpty()) {
          src_ = other.src_;
          onChanged();
        }
        if (other.getHasPermission() != false) {
          setHasPermission(other.getHasPermission());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object src_ = "";
      /**
       * <code>string src = 1;</code>
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string src = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder setSrc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder clearSrc() {
        
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>string src = 1;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        src_ = value;
        onChanged();
        return this;
      }

      private boolean hasPermission_ ;
      /**
       * <code>bool hasPermission = 2;</code>
       */
      public boolean getHasPermission() {
        return hasPermission_;
      }
      /**
       * <code>bool hasPermission = 2;</code>
       */
      public Builder setHasPermission(boolean value) {
        
        hasPermission_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool hasPermission = 2;</code>
       */
      public Builder clearHasPermission() {
        
        hasPermission_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.zrtcx.miniHDFS.protobuf.PathProto)
    }

    // @@protoc_insertion_point(class_scope:cn.zrtcx.miniHDFS.protobuf.PathProto)
    private static final cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto();
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PathProto>
        PARSER = new com.google.protobuf.AbstractParser<PathProto>() {
      public PathProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PathProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PathProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PathProto> getParserForType() {
      return PARSER;
    }

    public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.PathProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface IdProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.zrtcx.miniHDFS.protobuf.IdProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ip = 1;</code>
     */
    java.lang.String getIp();
    /**
     * <code>string ip = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpBytes();

    /**
     * <code>uint32 rpcPort = 2;</code>
     */
    int getRpcPort();

    /**
     * <code>uint32 socketPort = 3;</code>
     */
    int getSocketPort();
  }
  /**
   * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.IdProto}
   */
  public  static final class IdProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.zrtcx.miniHDFS.protobuf.IdProto)
      IdProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use IdProto.newBuilder() to construct.
    private IdProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private IdProto() {
      ip_ = "";
      rpcPort_ = 0;
      socketPort_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private IdProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              ip_ = s;
              break;
            }
            case 16: {

              rpcPort_ = input.readUInt32();
              break;
            }
            case 24: {

              socketPort_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder.class);
    }

    public static final int IP_FIELD_NUMBER = 1;
    private volatile java.lang.Object ip_;
    /**
     * <code>string ip = 1;</code>
     */
    public java.lang.String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ip_ = s;
        return s;
      }
    }
    /**
     * <code>string ip = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RPCPORT_FIELD_NUMBER = 2;
    private int rpcPort_;
    /**
     * <code>uint32 rpcPort = 2;</code>
     */
    public int getRpcPort() {
      return rpcPort_;
    }

    public static final int SOCKETPORT_FIELD_NUMBER = 3;
    private int socketPort_;
    /**
     * <code>uint32 socketPort = 3;</code>
     */
    public int getSocketPort() {
      return socketPort_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ip_);
      }
      if (rpcPort_ != 0) {
        output.writeUInt32(2, rpcPort_);
      }
      if (socketPort_ != 0) {
        output.writeUInt32(3, socketPort_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ip_);
      }
      if (rpcPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, rpcPort_);
      }
      if (socketPort_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, socketPort_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto)) {
        return super.equals(obj);
      }
      cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto other = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto) obj;

      boolean result = true;
      result = result && getIp()
          .equals(other.getIp());
      result = result && (getRpcPort()
          == other.getRpcPort());
      result = result && (getSocketPort()
          == other.getSocketPort());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IP_FIELD_NUMBER;
      hash = (53 * hash) + getIp().hashCode();
      hash = (37 * hash) + RPCPORT_FIELD_NUMBER;
      hash = (53 * hash) + getRpcPort();
      hash = (37 * hash) + SOCKETPORT_FIELD_NUMBER;
      hash = (53 * hash) + getSocketPort();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.IdProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.zrtcx.miniHDFS.protobuf.IdProto)
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder.class);
      }

      // Construct using cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        ip_ = "";

        rpcPort_ = 0;

        socketPort_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getDefaultInstanceForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.getDefaultInstance();
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto build() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto buildPartial() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto result = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto(this);
        result.ip_ = ip_;
        result.rpcPort_ = rpcPort_;
        result.socketPort_ = socketPort_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto) {
          return mergeFrom((cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto other) {
        if (other == cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.getDefaultInstance()) return this;
        if (!other.getIp().isEmpty()) {
          ip_ = other.ip_;
          onChanged();
        }
        if (other.getRpcPort() != 0) {
          setRpcPort(other.getRpcPort());
        }
        if (other.getSocketPort() != 0) {
          setSocketPort(other.getSocketPort());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object ip_ = "";
      /**
       * <code>string ip = 1;</code>
       */
      public java.lang.String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpBytes() {
        java.lang.Object ref = ip_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ip_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ip = 1;</code>
       */
      public Builder setIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       */
      public Builder clearIp() {
        
        ip_ = getDefaultInstance().getIp();
        onChanged();
        return this;
      }
      /**
       * <code>string ip = 1;</code>
       */
      public Builder setIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ip_ = value;
        onChanged();
        return this;
      }

      private int rpcPort_ ;
      /**
       * <code>uint32 rpcPort = 2;</code>
       */
      public int getRpcPort() {
        return rpcPort_;
      }
      /**
       * <code>uint32 rpcPort = 2;</code>
       */
      public Builder setRpcPort(int value) {
        
        rpcPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 rpcPort = 2;</code>
       */
      public Builder clearRpcPort() {
        
        rpcPort_ = 0;
        onChanged();
        return this;
      }

      private int socketPort_ ;
      /**
       * <code>uint32 socketPort = 3;</code>
       */
      public int getSocketPort() {
        return socketPort_;
      }
      /**
       * <code>uint32 socketPort = 3;</code>
       */
      public Builder setSocketPort(int value) {
        
        socketPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 socketPort = 3;</code>
       */
      public Builder clearSocketPort() {
        
        socketPort_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.zrtcx.miniHDFS.protobuf.IdProto)
    }

    // @@protoc_insertion_point(class_scope:cn.zrtcx.miniHDFS.protobuf.IdProto)
    private static final cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto();
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<IdProto>
        PARSER = new com.google.protobuf.AbstractParser<IdProto>() {
      public IdProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new IdProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<IdProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<IdProto> getParserForType() {
      return PARSER;
    }

    public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BlockProtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.zrtcx.miniHDFS.protobuf.BlockProto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getId();
    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder getIdOrBuilder();

    /**
     * <code>string src = 2;</code>
     */
    java.lang.String getSrc();
    /**
     * <code>string src = 2;</code>
     */
    com.google.protobuf.ByteString
        getSrcBytes();

    /**
     * <code>uint64 offset = 3;</code>
     */
    long getOffset();

    /**
     * <code>uint64 length = 4;</code>
     */
    long getLength();
  }
  /**
   * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.BlockProto}
   */
  public  static final class BlockProto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.zrtcx.miniHDFS.protobuf.BlockProto)
      BlockProtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BlockProto.newBuilder() to construct.
    private BlockProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BlockProto() {
      src_ = "";
      offset_ = 0L;
      length_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BlockProto(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder subBuilder = null;
              if (id_ != null) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              src_ = s;
              break;
            }
            case 24: {

              offset_ = input.readUInt64();
              break;
            }
            case 32: {

              length_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto id_;
    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    public boolean hasId() {
      return id_ != null;
    }
    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getId() {
      return id_ == null ? cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.getDefaultInstance() : id_;
    }
    /**
     * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
     */
    public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder getIdOrBuilder() {
      return getId();
    }

    public static final int SRC_FIELD_NUMBER = 2;
    private volatile java.lang.Object src_;
    /**
     * <code>string src = 2;</code>
     */
    public java.lang.String getSrc() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        src_ = s;
        return s;
      }
    }
    /**
     * <code>string src = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSrcBytes() {
      java.lang.Object ref = src_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        src_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int OFFSET_FIELD_NUMBER = 3;
    private long offset_;
    /**
     * <code>uint64 offset = 3;</code>
     */
    public long getOffset() {
      return offset_;
    }

    public static final int LENGTH_FIELD_NUMBER = 4;
    private long length_;
    /**
     * <code>uint64 length = 4;</code>
     */
    public long getLength() {
      return length_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != null) {
        output.writeMessage(1, getId());
      }
      if (!getSrcBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, src_);
      }
      if (offset_ != 0L) {
        output.writeUInt64(3, offset_);
      }
      if (length_ != 0L) {
        output.writeUInt64(4, length_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getId());
      }
      if (!getSrcBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, src_);
      }
      if (offset_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, offset_);
      }
      if (length_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, length_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto)) {
        return super.equals(obj);
      }
      cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto other = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && getId()
            .equals(other.getId());
      }
      result = result && getSrc()
          .equals(other.getSrc());
      result = result && (getOffset()
          == other.getOffset());
      result = result && (getLength()
          == other.getLength());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      hash = (37 * hash) + SRC_FIELD_NUMBER;
      hash = (53 * hash) + getSrc().hashCode();
      hash = (37 * hash) + OFFSET_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOffset());
      hash = (37 * hash) + LENGTH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLength());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.zrtcx.miniHDFS.protobuf.BlockProto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.zrtcx.miniHDFS.protobuf.BlockProto)
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.class, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.Builder.class);
      }

      // Construct using cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (idBuilder_ == null) {
          id_ = null;
        } else {
          id_ = null;
          idBuilder_ = null;
        }
        src_ = "";

        offset_ = 0L;

        length_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto getDefaultInstanceForType() {
        return cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.getDefaultInstance();
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto build() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto buildPartial() {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto result = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto(this);
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        result.src_ = src_;
        result.offset_ = offset_;
        result.length_ = length_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto) {
          return mergeFrom((cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto other) {
        if (other == cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto.getDefaultInstance()) return this;
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (!other.getSrc().isEmpty()) {
          src_ = other.src_;
          onChanged();
        }
        if (other.getOffset() != 0L) {
          setOffset(other.getOffset());
        }
        if (other.getLength() != 0L) {
          setLength(other.getLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto id_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder> idBuilder_;
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public boolean hasId() {
        return idBuilder_ != null || id_ != null;
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto getId() {
        if (idBuilder_ == null) {
          return id_ == null ? cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.getDefaultInstance() : id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public Builder setId(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public Builder setId(
          cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public Builder mergeId(cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto value) {
        if (idBuilder_ == null) {
          if (id_ != null) {
            id_ =
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = null;
          onChanged();
        } else {
          id_ = null;
          idBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder getIdBuilder() {
        
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_ == null ?
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.getDefaultInstance() : id_;
        }
      }
      /**
       * <code>.cn.zrtcx.miniHDFS.protobuf.IdProto id = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProto.Builder, cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.IdProtoOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private java.lang.Object src_ = "";
      /**
       * <code>string src = 2;</code>
       */
      public java.lang.String getSrc() {
        java.lang.Object ref = src_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          src_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string src = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSrcBytes() {
        java.lang.Object ref = src_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          src_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string src = 2;</code>
       */
      public Builder setSrc(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        src_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string src = 2;</code>
       */
      public Builder clearSrc() {
        
        src_ = getDefaultInstance().getSrc();
        onChanged();
        return this;
      }
      /**
       * <code>string src = 2;</code>
       */
      public Builder setSrcBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        src_ = value;
        onChanged();
        return this;
      }

      private long offset_ ;
      /**
       * <code>uint64 offset = 3;</code>
       */
      public long getOffset() {
        return offset_;
      }
      /**
       * <code>uint64 offset = 3;</code>
       */
      public Builder setOffset(long value) {
        
        offset_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 offset = 3;</code>
       */
      public Builder clearOffset() {
        
        offset_ = 0L;
        onChanged();
        return this;
      }

      private long length_ ;
      /**
       * <code>uint64 length = 4;</code>
       */
      public long getLength() {
        return length_;
      }
      /**
       * <code>uint64 length = 4;</code>
       */
      public Builder setLength(long value) {
        
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 length = 4;</code>
       */
      public Builder clearLength() {
        
        length_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.zrtcx.miniHDFS.protobuf.BlockProto)
    }

    // @@protoc_insertion_point(class_scope:cn.zrtcx.miniHDFS.protobuf.BlockProto)
    private static final cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto();
    }

    public static cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BlockProto>
        PARSER = new com.google.protobuf.AbstractParser<BlockProto>() {
      public BlockProto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new BlockProto(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BlockProto> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BlockProto> getParserForType() {
      return PARSER;
    }

    public cn.zrtcx.miniHDFS.protobuf.BaseProtocolProbuf.BlockProto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022BaseProtocol.proto\022\032cn.zrtcx.miniHDFS." +
      "protobuf\"/\n\tPathProto\022\013\n\003src\030\001 \001(\t\022\025\n\rha" +
      "sPermission\030\002 \001(\010\":\n\007IdProto\022\n\n\002ip\030\001 \001(\t" +
      "\022\017\n\007rpcPort\030\002 \001(\r\022\022\n\nsocketPort\030\003 \001(\r\"j\n" +
      "\nBlockProto\022/\n\002id\030\001 \001(\0132#.cn.zrtcx.miniH" +
      "DFS.protobuf.IdProto\022\013\n\003src\030\002 \001(\t\022\016\n\006off" +
      "set\030\003 \001(\004\022\016\n\006length\030\004 \001(\004B0\n\032cn.zrtcx.mi" +
      "niHDFS.protobufB\022BaseProtocolProbufb\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zrtcx_miniHDFS_protobuf_PathProto_descriptor,
        new java.lang.String[] { "Src", "HasPermission", });
    internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zrtcx_miniHDFS_protobuf_IdProto_descriptor,
        new java.lang.String[] { "Ip", "RpcPort", "SocketPort", });
    internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_zrtcx_miniHDFS_protobuf_BlockProto_descriptor,
        new java.lang.String[] { "Id", "Src", "Offset", "Length", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
